// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: proto/user_message.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	UserService_GetUserByID_FullMethodName   = "/user.UserService/GetUserByID"
	UserService_GetUsersByIDs_FullMethodName = "/user.UserService/GetUsersByIDs"
	UserService_SearchUsers_FullMethodName   = "/user.UserService/SearchUsers"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserByID(ctx context.Context, in *UserIDs, opts ...grpc.CallOption) (*User, error)
	GetUsersByIDs(ctx context.Context, in *UserIDs, opts ...grpc.CallOption) (UserService_GetUsersByIDsClient, error)
	SearchUsers(ctx context.Context, in *User, opts ...grpc.CallOption) (UserService_SearchUsersClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserByID(ctx context.Context, in *UserIDs, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserService_GetUserByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsersByIDs(ctx context.Context, in *UserIDs, opts ...grpc.CallOption) (UserService_GetUsersByIDsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_GetUsersByIDs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceGetUsersByIDsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_GetUsersByIDsClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceGetUsersByIDsClient struct {
	grpc.ClientStream
}

func (x *userServiceGetUsersByIDsClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) SearchUsers(ctx context.Context, in *User, opts ...grpc.CallOption) (UserService_SearchUsersClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], UserService_SearchUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceSearchUsersClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_SearchUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceSearchUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceSearchUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetUserByID(context.Context, *UserIDs) (*User, error)
	GetUsersByIDs(*UserIDs, UserService_GetUsersByIDsServer) error
	SearchUsers(*User, UserService_SearchUsersServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetUserByID(context.Context, *UserIDs) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (UnimplementedUserServiceServer) GetUsersByIDs(*UserIDs, UserService_GetUsersByIDsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUsersByIDs not implemented")
}
func (UnimplementedUserServiceServer) SearchUsers(*User, UserService_SearchUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByID(ctx, req.(*UserIDs))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsersByIDs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserIDs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).GetUsersByIDs(m, &userServiceGetUsersByIDsServer{ServerStream: stream})
}

type UserService_GetUsersByIDsServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceGetUsersByIDsServer struct {
	grpc.ServerStream
}

func (x *userServiceGetUsersByIDsServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_SearchUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(User)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).SearchUsers(m, &userServiceSearchUsersServer{ServerStream: stream})
}

type UserService_SearchUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceSearchUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceSearchUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByID",
			Handler:    _UserService_GetUserByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUsersByIDs",
			Handler:       _UserService_GetUsersByIDs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchUsers",
			Handler:       _UserService_SearchUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/user_message.proto",
}
